@module("braid-design-system") @react.component
external make: (
  ~background: [
    | #body
    | #brand
    | #brandAccent
    | #brandAccentActive
    | #brandAccentHover
    | #brandAccentSoft
    | #brandAccentSoftActive
    | #brandAccentSoftHover
    | #caution
    | #cautionLight
    | #critical
    | #criticalActive
    | #criticalHover
    | #criticalLight
    | #criticalSoft
    | #criticalSoftActive
    | #criticalSoftHover
    | #formAccent
    | #formAccentActive
    | #formAccentHover
    | #formAccentSoft
    | #formAccentSoftActive
    | #formAccentSoftHover
    | #info
    | #infoLight
    | #neutral
    | #neutralActive
    | #neutralHover
    | #neutralLight
    | #neutralSoft
    | #neutralSoftActive
    | #neutralSoftHover
    | #positive
    | #positiveLight
    | #promote
    | #promoteLight
    | #surface
    | #customDark
    | #customLight
  ]=?,
  ~boxShadow: [
    | #small
    | #large
    | #medium
    | #borderBrandAccentLarge
    | #borderBrandAccentLightLarge
    | #borderCaution
    | #borderCautionLight
    | #borderCritical
    | #borderCriticalLarge
    | #borderCriticalLight
    | #borderCriticalLightLarge
    | #borderField
    | #borderFormAccent
    | #borderFormAccentLarge
    | #borderFormAccentLight
    | #borderFormAccentLightLarge
    | #borderInfo
    | #borderInfoLight
    | #borderNeutral
    | #borderNeutralLarge
    | #borderNeutralInverted
    | #borderNeutralInvertedLarge
    | #borderNeutralLight
    | #borderPositive
    | #borderPositiveLight
    | #borderPromote
    | #borderPromoteLight
    | #outlineFocus
  ]=?,
  ~component: [
    | #symbol
    | #object
    | #slot
    | #style
    | #title
    | #text
    | #small
    | #strong
    | #body
    | #link
    | #clipPath
    | #filter
    | #mask
    | #marker
    | #progress
    | #ruby
    | #table
    | #cite
    | #data
    | #form
    | #label
    | #pattern
    | #span
    | #summary
    | #div
    | #a
    | #abbr
    | #address
    | #area
    | #article
    | #aside
    | #audio
    | #b
    | #base
    | #bdi
    | #bdo
    | #big
    | #blockquote
    | #br
    | #button
    | #canvas
    | #caption
    | #code
    | #col
    | #colgroup
    | #datalist
    | #dd
    | #del
    | #details
    | #dfn
    | #dialog
    | #dl
    | #dt
    | #em
    | #embed
    | #fieldset
    | #figcaption
    | #figure
    | #footer
    | #h1
    | #h2
    | #h3
    | #h4
    | #h5
    | #h6
    | #head
    | #header
    | #hgroup
    | #hr
    | #html
    | #i
    | #iframe
    | #img
    | #input
    | #ins
    | #kbd
    | #keygen
    | #legend
    | #li
    | #main
    | #map
    | #mark
    | #menu
    | #menuitem
    | #meta
    | #meter
    | #nav
    | #noindex
    | #noscript
    | #ol
    | #optgroup
    | #option
    | #output
    | #p
    | #param
    | #picture
    | #pre
    | #q
    | #rp
    | #rt
    | #s
    | #samp
    | #script
    | #section
    | #select
    | #source
    | #sub
    | #sup
    | #template
    | #tbody
    | #td
    | #textarea
    | #tfoot
    | #th
    | #thead
    | #time
    | #tr
    | #track
    | #u
    | #ul
    | #var
    | #video
    | #wbr
    | #webview
    | #svg
    | #animate
    | #animateMotion
    | #animateTransform
    | #circle
    | #defs
    | #desc
    | #ellipse
    | #feBlend
    | #feColorMatrix
    | #feComponentTransfer
    | #feComposite
    | #feConvolveMatrix
    | #feDiffuseLighting
    | #feDisplacementMap
    | #feDistantLight
    | #feDropShadow
    | #feFlood
    | #feFuncA
    | #feFuncB
    | #feFuncG
    | #feFuncR
    | #feGaussianBlur
    | #feImage
    | #feMerge
    | #feMergeNode
    | #feMorphology
    | #feOffset
    | #fePointLight
    | #feSpecularLighting
    | #feSpotLight
    | #feTile
    | #feTurbulence
    | #foreignObject
    | #g
    | #image
    | #line
    | #linearGradient
    | #metadata
    | #mpath
    | #path
    | #polygon
    | #polyline
    | #radialGradient
    | #rect
    | #stop
    | #"switch"
    | #textPath
    | #tspan
    | #use
    | #view
  ]=?,
  ~borderRadius: Braid__Prop.propObject<
    [
      | #standard
      | #large
      | #none
      | #xlarge
      | #full
    ],
  >=?,
  ~padding: Braid__Prop.space=?,
  ~children: React.element=?,
) => React.element = "Box"
